### ISSUE TITLE
Common records

### ISSUE THREAD

**Issue by gabriel** [keybase/protocol#3]
We should get some base models. I'm working on displaying the logged in user profile (and from there can generate proofs.) and would be to have some common records/models:

Maybe something like:

```
record User {
  string uid;
  string username;
  string fullname;
  string bio;
  string location;
  array<Image> images;
  array<Key> keys; 
  array<Proof> proofs;
  array<CryptoCurrency> cryptoAddresses;
}

record Key {
  // ?
}

record Image {
  string url;
}

record Proof {
  string id;
  string sigId;
  string nameTag;
  string service; // proofType?
  string url;
}
```

BTW, these are the models I use in the HTTP API: https://github.com/gabriel/KBKeybase/blob/master/KBKeybase/Models
(that these records are based on)

Right now I am using KBKeybase models above in mocks (will be easy to transition to whatever models we use here.)

**Comment by gabriel** [comment]
Oops I just saw identify_ui.avdl stuff which has RemoteProof and Cryptocurrency etc.

I guess what would be useful is a User or Identity? record after I log in and in status (UserInfo -> User)?

And also a way to load a user record based on a list of usernames or maybe tracking list?

**Comment by maxtaco** [comment]
Going to be AFK a bit this weekend.  The identify_ui.avdl in its current form is for tracking, in which information kind of dribbles back to the view (like did your hackernews proof check out)?  

We might need other models for the same sorts of data....

**Comment by gabriel** [comment]
ok cool, yeah I'll use the identify stuff
